USE [master]
GO

/****** Object:  Database [HashStore]    Script Date: 20.08.2017 1:47:13 ******/
CREATE DATABASE [HashStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HashStore', FILENAME = N'C:\Users\Admin\HashStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HashStore_log', FILENAME = N'C:\Users\Admin\HashStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [HashStore] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HashStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HashStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HashStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HashStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HashStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HashStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [HashStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HashStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HashStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HashStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HashStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HashStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HashStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HashStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HashStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HashStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HashStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HashStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HashStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HashStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HashStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HashStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HashStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HashStore] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HashStore] SET  MULTI_USER 
GO

ALTER DATABASE [HashStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HashStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HashStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HashStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HashStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HashStore] SET QUERY_STORE = OFF
GO

USE [HashStore]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [HashStore] SET  READ_WRITE 
GO


USE [HashStore]
GO

/****** Object:  Table [dbo].[file]    Script Date: 20.08.2017 1:38:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[file](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Filename] [nvarchar](max) NULL,
	[Hash] [nvarchar](max) NULL,
	[CreatedAt] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.file] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


USE [HashStore]
GO

/****** Object:  Table [dbo].[log]    Script Date: 20.08.2017 1:47:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[log](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Message] [nvarchar](max) NULL,
	[CreatedAt] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.log] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


